# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190609_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldate', models.CharField(max_length=30, verbose_name='时间')),
                ('luser', models.CharField(max_length=20, verbose_name='姓名')),
                ('operate', models.CharField(choices=[('login', '登录'), ('exit', '退出'), ('exam', '考试'), ('score', '查询成绩')], max_length=20, verbose_name='操作')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'log',
            },
        ),
        migrations.RemoveField(
            model_name='grade',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='tid',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
