# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='examtime',
            field=models.DateTimeField(verbose_name='考试时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('3', 'difficult'), ('1', 'easy')], max_length=10, verbose_name='等级'),
        ),
    ]
